services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tkgling/chatgpt-discord-bot:latest
    restart: always
    environment:
      DISCORD_TOKEN: $DISCORD_TOKEN
      GUILD_ID: $GUILD_ID
      APPLICATION_ID: $APPLICATION_ID
      CHANNEL_ID: $CHANNEL_ID