services:
  app:
    image: tkgling/chatgpt-discord-bot:latest
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: $DISCORD_TOKEN
      GUILD_ID: $GUILD_ID
      APPLICATION_ID: $APPLICATION_ID
      CHANNEL_ID: $CHANNEL_ID