services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt-discord-bot
    restart: always
    environment:
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_DEFAULT_MODEL: $OPENAI_DEFAULT_MODEL
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      DISCORD_GUILD_ID: $DISCORD_GUILD_ID
      DISCORD_APPLICATION_ID: $DISCORD_APPLICATION_ID
      DISCORD_CHANNEL_ID: $DISCORD_CHANNEL_ID
